# Generated by Django 6.0.1 on 2026-02-09 14:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('quantidade_inicial', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('quantidade_restante', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_estoque', to='compras.compra')),
                ('item_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='compras.itemcompra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='compras.produto')),
            ],
            options={
                'ordering': ['data_entrada', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EstoqueMovimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste')], db_index=True, max_length=10)),
                ('quantidade', models.DecimalField(db_index=True, decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('data_movimento', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('observacao', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_estoque', to='compras.compra')),
                ('item_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_estoque', to='compras.itemcompra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='compras.produto')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos', to='estoque.lote')),
            ],
            options={
                'ordering': ['-data_movimento', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_atual', models.DecimalField(db_index=True, decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('estoque_ideal', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('estoque_maximo', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estoque_cfg', to='compras.produto')),
            ],
            options={
                'ordering': ['produto__nome'],
            },
        ),
        migrations.CreateModel(
            name='AlertaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('RESOLVIDO', 'Resolvido')], db_index=True, default='ABERTO', max_length=10)),
                ('saldo_no_momento', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('minimo_configurado', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_estoque', to='compras.produto')),
            ],
            options={
                'ordering': ['status', '-criado_em', '-id'],
                'indexes': [models.Index(fields=['status', 'criado_em'], name='idx_alerta_status_data'), models.Index(fields=['produto', 'status'], name='idx_alerta_prod_status')],
            },
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['produto', 'data_entrada'], name='idx_lote_prod_data'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['quantidade_restante'], name='idx_lote_restante'),
        ),
        migrations.AddIndex(
            model_name='estoquemovimento',
            index=models.Index(fields=['produto', 'data_movimento'], name='idx_mov_prod_data'),
        ),
        migrations.AddIndex(
            model_name='estoquemovimento',
            index=models.Index(fields=['tipo', 'data_movimento'], name='idx_mov_tipo_data'),
        ),
        migrations.AddIndex(
            model_name='produtoestoque',
            index=models.Index(fields=['saldo_atual'], name='idx_prodestoque_saldo'),
        ),
        migrations.AddIndex(
            model_name='produtoestoque',
            index=models.Index(fields=['estoque_minimo'], name='idx_prodestoque_min'),
        ),
    ]
