# Generated by Django 6.0.2 on 2026-02-24 12:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_unidades(apps, schema_editor):
    ProdutoEstoque = apps.get_model("estoque", "ProdutoEstoque")
    ProdutoEstoqueUnidade = apps.get_model("estoque", "ProdutoEstoqueUnidade")
    for cfg in ProdutoEstoque.objects.all().iterator():
        rows = list(ProdutoEstoqueUnidade.objects.filter(produto_id=cfg.produto_id))
        if not rows:
            ProdutoEstoqueUnidade.objects.create(
                produto_id=cfg.produto_id,
                unidade="LOJA_1",
                saldo_atual=(cfg.saldo_atual or Decimal("0.000")),
            )
            ProdutoEstoqueUnidade.objects.create(
                produto_id=cfg.produto_id,
                unidade="LOJA_2",
                saldo_atual=Decimal("0.000"),
            )
            continue
        presentes = {r.unidade for r in rows}
        if "LOJA_1" not in presentes:
            ProdutoEstoqueUnidade.objects.create(
                produto_id=cfg.produto_id,
                unidade="LOJA_1",
                saldo_atual=Decimal("0.000"),
            )
        if "LOJA_2" not in presentes:
            ProdutoEstoqueUnidade.objects.create(
                produto_id=cfg.produto_id,
                unidade="LOJA_2",
                saldo_atual=Decimal("0.000"),
            )


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_add_compra_orcamentos_workflow'),
        ('estoque', '0004_transferencia_lote_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoestoqueunidade',
            name='unidade',
            field=models.CharField(choices=[('LOJA_1', 'FM COMERCIO - LOJA 1'), ('LOJA_2', 'ML COMERCIO - LOJA 2')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='transferenciaestoque',
            name='data_transferencia',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='transferenciaestoque',
            name='unidade_destino',
            field=models.CharField(choices=[('LOJA_1', 'FM COMERCIO - LOJA 1'), ('LOJA_2', 'ML COMERCIO - LOJA 2')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='transferenciaestoque',
            name='unidade_origem',
            field=models.CharField(choices=[('LOJA_1', 'FM COMERCIO - LOJA 1'), ('LOJA_2', 'ML COMERCIO - LOJA 2')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='SaidaOperacionalEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(choices=[('LOJA_1', 'FM COMERCIO - LOJA 1'), ('LOJA_2', 'ML COMERCIO - LOJA 2')], db_index=True, max_length=20)),
                ('tipo', models.CharField(choices=[('TROCA', 'Troca'), ('GARANTIA', 'Garantia'), ('AVARIA', 'Avaria'), ('OUTRA', 'Outra')], db_index=True, max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('data_saida', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('observacao', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('movimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saidas_operacionais', to='estoque.estoquemovimento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saidas_operacionais', to='compras.produto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_saida', '-id'],
                'indexes': [models.Index(fields=['data_saida'], name='idx_saidaop_data'), models.Index(fields=['tipo', 'data_saida'], name='idx_saidaop_tipo_data'), models.Index(fields=['unidade', 'produto'], name='idx_saidaop_unid_prod')],
            },
        ),
        migrations.RunPython(backfill_unidades, migrations.RunPython.noop),
    ]
