# Generated by Django 6.0.2 on 2026-02-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alter_produtoestoqueunidade_unidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoestoqueunidade',
            name='unidade',
            field=models.CharField(choices=[('LOJA_1', 'FM COMERCIO - UNIDADE 1'), ('LOJA_2', 'ML COMERCIO - UNIDADE 2')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='saidaoperacionalestoque',
            name='unidade',
            field=models.CharField(choices=[('LOJA_1', 'FM COMERCIO - UNIDADE 1'), ('LOJA_2', 'ML COMERCIO - UNIDADE 2')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='transferenciaestoque',
            name='unidade_destino',
            field=models.CharField(choices=[('LOJA_1', 'FM COMERCIO - UNIDADE 1'), ('LOJA_2', 'ML COMERCIO - UNIDADE 2')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='transferenciaestoque',
            name='unidade_origem',
            field=models.CharField(choices=[('LOJA_1', 'FM COMERCIO - UNIDADE 1'), ('LOJA_2', 'ML COMERCIO - UNIDADE 2')], db_index=True, max_length=20),
        ),
    ]
