# Generated by Django 6.0.2 on 2026-02-18 06:22

import django.db.models.deletion
import importadores.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0007_add_compra_status_evento'),
        ('estoque', '0004_transferencia_lote_ref'),
        ('financeiro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaixaRelatorioImportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField(db_index=True)),
                ('unidade', models.CharField(choices=[('LOJA_1', 'Loja 1'), ('LOJA_2', 'Loja 2')], db_index=True, max_length=20)),
                ('empresa_nome', models.CharField(blank=True, default='', max_length=120)),
                ('arquivo_pdf', models.FileField(upload_to=importadores.models.caixa_pdf_upload_path)),
                ('arquivo_nome', models.CharField(blank=True, default='', max_length=255)),
                ('arquivo_hash', models.CharField(db_index=True, max_length=64)),
                ('total_vendas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('SUCESSO', 'Sucesso'), ('PARCIAL', 'Parcial'), ('ERRO', 'Erro')], db_index=True, default='SUCESSO', max_length=20)),
                ('itens_detectados', models.PositiveIntegerField(default=0)),
                ('itens_baixados', models.PositiveIntegerField(default=0)),
                ('itens_inconsistentes', models.PositiveIntegerField(default=0)),
                ('log_erro', models.TextField(blank=True, default='')),
                ('observacoes', models.JSONField(blank=True, default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importacoes_caixa_pdf', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_referencia', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CaixaImportacaoInconsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default='', max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('detalhes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inconsistencias', to='importadores.caixarelatorioimportacao')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CaixaRelatorioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_mercadoria', models.CharField(db_index=True, max_length=50)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('quantidade', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('estoque_baixado', models.BooleanField(default=False)),
                ('mensagem', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='importadores.caixarelatorioimportacao')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='compras.produto')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoVendaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(choices=[('LOJA_1', 'Loja 1'), ('LOJA_2', 'Loja 2')], db_index=True, max_length=20)),
                ('tipo', models.CharField(db_index=True, default='VENDA', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_venda', to='importadores.caixarelatorioimportacao')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_venda', to='importadores.caixarelatorioitem')),
                ('movimento_estoque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_venda_pdf', to='estoque.estoquemovimento')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeContaFinanceiraConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(choices=[('LOJA_1', 'Loja 1'), ('LOJA_2', 'Loja 2')], max_length=20, unique=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='config_unidades', to='financeiro.contabancaria')),
            ],
            options={
                'verbose_name': 'Config unidade x conta financeira',
                'verbose_name_plural': 'Config unidade x conta financeira',
            },
        ),
        migrations.AddIndex(
            model_name='caixarelatorioimportacao',
            index=models.Index(fields=['unidade', 'data_referencia'], name='idx_caixa_pdf_unid_data'),
        ),
        migrations.AddIndex(
            model_name='caixarelatorioimportacao',
            index=models.Index(fields=['status', 'criado_em'], name='idx_caixa_pdf_status_data'),
        ),
        migrations.AddConstraint(
            model_name='caixarelatorioimportacao',
            constraint=models.UniqueConstraint(fields=('arquivo_hash', 'data_referencia', 'unidade'), name='uniq_caixa_pdf_hash_data_unidade'),
        ),
        migrations.AddIndex(
            model_name='caixarelatorioitem',
            index=models.Index(fields=['importacao', 'codigo_mercadoria'], name='idx_caixa_item_imp_cod'),
        ),
        migrations.AddConstraint(
            model_name='movimentovendaestoque',
            constraint=models.UniqueConstraint(fields=('item', 'movimento_estoque'), name='uniq_mov_venda_item_mov'),
        ),
    ]
