# Generated by Django 6.0.2 on 2026-02-18 06:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixarelatorioimportacao',
            name='total_trocas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='caixarelatorioimportacao',
            name='vendas_detalhadas',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
