# Generated by Django 6.0.2 on 2026-02-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importadores', '0002_caixarelatorioimportacao_total_trocas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixarelatorioimportacao',
            name='unidade',
            field=models.CharField(choices=[('LOJA_1', 'FM COMERCIO - LOJA 1'), ('LOJA_2', 'ML COMERCIO - LOJA 2')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='movimentovendaestoque',
            name='unidade',
            field=models.CharField(choices=[('LOJA_1', 'FM COMERCIO - LOJA 1'), ('LOJA_2', 'ML COMERCIO - LOJA 2')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='unidadecontafinanceiraconfig',
            name='unidade',
            field=models.CharField(choices=[('LOJA_1', 'FM COMERCIO - LOJA 1'), ('LOJA_2', 'ML COMERCIO - LOJA 2')], max_length=20, unique=True),
        ),
    ]
