# Generated by Django 6.0.1 on 2026-02-10 17:35

import contas.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('FM', 'FM'), ('ML', 'ML'), ('PESSOAL', 'PESSOAL'), ('FM/ML', 'FM/ML'), ('OUTROS', 'OUTROS')], max_length=20, unique=True)),
                ('nome', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='RegraImposto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Regra padrão', max_length=100)),
                ('percentual', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ativo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nome_normalizado', models.CharField(db_index=True, max_length=255, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome_normalizado'], name='idx_cat_nome_norm')],
            },
        ),
        migrations.CreateModel(
            name='CategoriaAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nome_normalizado', models.CharField(db_index=True, max_length=255, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='contas.categoria')),
            ],
            options={
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome_normalizado'], name='idx_catalias_nome_norm'), models.Index(fields=['principal'], name='idx_catalias_principal')],
            },
        ),
        migrations.CreateModel(
            name='ContaAPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vencimento', models.DateField(db_index=True)),
                ('descricao', models.CharField(db_index=True, max_length=255)),
                ('centro_custo', models.CharField(choices=[('FM', 'FM'), ('ML', 'ML'), ('PESSOAL', 'PESSOAL'), ('FM/ML', 'FM/ML'), ('OUTROS', 'OUTROS')], db_index=True, max_length=20)),
                ('valor', models.DecimalField(db_index=True, decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('PAGA', 'Paga')], db_index=True, default='ABERTA', max_length=10)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to=contas.models.comprovante_upload_path)),
                ('exige_comprovante', models.BooleanField(db_index=True, default=True)),
                ('importado', models.BooleanField(db_index=True, default=False)),
                ('fonte_importacao', models.CharField(blank=True, default='', max_length=120)),
                ('linha_importacao', models.IntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas', to='contas.categoria')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas', to='compras.fornecedor')),
            ],
            options={
                'ordering': ['-vencimento', '-id'],
                'indexes': [models.Index(fields=['status', 'vencimento'], name='idx_conta_status_data'), models.Index(fields=['centro_custo', 'vencimento'], name='idx_conta_cc_data'), models.Index(fields=['categoria', 'vencimento'], name='idx_conta_cat_data')],
            },
        ),
        migrations.CreateModel(
            name='ProjecaoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('centro_custo', models.CharField(choices=[('FM', 'FM'), ('ML', 'ML'), ('PESSOAL', 'PESSOAL'), ('FM/ML', 'FM/ML'), ('OUTROS', 'OUTROS')], db_index=True, max_length=20)),
                ('valor_previsto', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contas.categoria')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.fornecedor')),
            ],
            options={
                'ordering': ['-ativo', 'descricao'],
                'indexes': [models.Index(fields=['centro_custo'], name='idx_proj_cc'), models.Index(fields=['ativo'], name='idx_proj_ativo')],
            },
        ),
    ]
