# Generated by Django 6.0.1 on 2026-02-10 19:02

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='categoriaalias',
            name='idx_catalias_nome_norm',
        ),
        migrations.RemoveIndex(
            model_name='categoriaalias',
            name='idx_catalias_principal',
        ),
        migrations.DeleteModel(
            name='CentroCusto',
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projecaomensal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='regraimposto',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='categoria',
            name='idx_cat_nome_norm',
        ),
        migrations.RemoveIndex(
            model_name='contaapagar',
            name='idx_conta_cat_data',
        ),
        migrations.RemoveIndex(
            model_name='projecaomensal',
            name='idx_proj_cc',
        ),
        migrations.RemoveIndex(
            model_name='projecaomensal',
            name='idx_proj_ativo',
        ),
        migrations.RenameIndex(
            model_name='contaapagar',
            new_name='idx_conta_status_venc',
            old_name='idx_conta_status_data',
        ),
        migrations.RenameIndex(
            model_name='contaapagar',
            new_name='idx_conta_cc_venc',
            old_name='idx_conta_cc_data',
        ),
        migrations.RemoveField(
            model_name='regraimposto',
            name='percentual',
        ),
        migrations.AddField(
            model_name='contaapagar',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contaapagar',
            name='boleto',
            field=models.FileField(blank=True, null=True, upload_to='contas/boletos/'),
        ),
        migrations.AddField(
            model_name='contaapagar',
            name='exige_boleto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contaapagar',
            name='exige_nota_fiscal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contaapagar',
            name='nota_fiscal',
            field=models.FileField(blank=True, null=True, upload_to='contas/notas_fiscais/'),
        ),
        migrations.AddField(
            model_name='projecaomensal',
            name='nome',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='projecaomensal',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='regraimposto',
            name='aliquota_percentual',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='contaapagar',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_a_pagar', to='contas.categoria'),
        ),
        migrations.AlterField(
            model_name='contaapagar',
            name='centro_custo',
            field=models.CharField(choices=[('FM', 'FM'), ('ML', 'ML'), ('PESSOAL', 'PESSOAL'), ('FM/ML', 'FM/ML'), ('OUTROS', 'OUTROS')], db_index=True, default='OUTROS', max_length=20),
        ),
        migrations.AlterField(
            model_name='contaapagar',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='contas/comprovantes/'),
        ),
        migrations.AlterField(
            model_name='contaapagar',
            name='criado_em',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contaapagar',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contaapagar',
            name='exige_comprovante',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contaapagar',
            name='fonte_importacao',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='contaapagar',
            name='pago_em',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contaapagar',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'ABERTA'), ('PAGA', 'PAGA'), ('CANCELADA', 'CANCELADA')], db_index=True, default='ABERTA', max_length=20),
        ),
        migrations.AlterField(
            model_name='contaapagar',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='projecaomensal',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projecoes_mensais', to='contas.categoria'),
        ),
        migrations.AlterField(
            model_name='projecaomensal',
            name='centro_custo',
            field=models.CharField(choices=[('FM', 'FM'), ('ML', 'ML'), ('PESSOAL', 'PESSOAL'), ('FM/ML', 'FM/ML'), ('OUTROS', 'OUTROS')], default='OUTROS', max_length=20),
        ),
        migrations.AlterField(
            model_name='regraimposto',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='regraimposto',
            name='nome',
            field=models.CharField(default='Regra padrão', max_length=120),
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='nome_normalizado',
        ),
        migrations.RemoveField(
            model_name='contaapagar',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='projecaomensal',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='projecaomensal',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='projecaomensal',
            name='valor_previsto',
        ),
        migrations.DeleteModel(
            name='CategoriaAlias',
        ),
    ]
