# Generated by Django 6.0.2 on 2026-02-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_remove_categoriaalias_idx_catalias_nome_norm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaapagar',
            name='pedido',
            field=models.FileField(blank=True, null=True, upload_to='contas/pedidos/'),
        ),
    ]
