# Generated by Django 6.0 on 2026-02-21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("boletos", "0006_add_necessita_comprovante"),
        ("compras", "0007_add_compra_status_evento"),
        ("estoque", "0004_transferencia_lote_ref"),
        ("financeiro", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venda",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data_venda", models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ("status", models.CharField(choices=[("RASCUNHO", "Rascunho"), ("CONFIRMADA", "Confirmada"), ("FATURADA", "Faturada"), ("FINALIZADA", "Finalizada"), ("CANCELADA", "Cancelada")], db_index=True, default="RASCUNHO", max_length=20)),
                ("tipo_pagamento", models.CharField(choices=[("AVISTA", "A vista"), ("PARCELADO", "Parcelado"), ("PARCELADO_BOLETO", "Parcelado com boleto")], db_index=True, default="AVISTA", max_length=25)),
                ("numero_parcelas", models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(36)])),
                ("intervalo_parcelas_dias", models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ("primeiro_vencimento", models.DateField(blank=True, db_index=True, null=True)),
                ("subtotal", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("desconto_total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("acrescimo", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("total_final", models.DecimalField(db_index=True, decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("observacoes", models.TextField(blank=True, default="")),
                ("faturada_em", models.DateTimeField(blank=True, null=True)),
                ("cancelada_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("cancelada_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="vendas_canceladas", to=settings.AUTH_USER_MODEL)),
                ("cliente", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="vendas", to="boletos.cliente")),
                ("faturada_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="vendas_faturadas", to=settings.AUTH_USER_MODEL)),
                ("vendedor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="vendas_registradas", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-data_venda", "-id"],
                "indexes": [
                    models.Index(fields=["status", "data_venda"], name="idx_venda_status_data"),
                    models.Index(fields=["cliente", "data_venda"], name="idx_venda_cliente_data"),
                    models.Index(fields=["tipo_pagamento", "data_venda"], name="idx_venda_pgto_data"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ItemVenda",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantidade", models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0.001"))])),
                ("preco_unitario", models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal("0.00"))])),
                ("desconto", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal("0.00"))])),
                ("subtotal", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("produto", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="itens_venda", to="compras.produto")),
                ("venda", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="itens", to="vendas.venda")),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["venda"], name="idx_itemvenda_venda"),
                    models.Index(fields=["produto"], name="idx_itemvenda_produto"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VendaEvento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo", models.CharField(choices=[("CRIACAO", "Criacao"), ("CONFIRMACAO", "Confirmacao"), ("FATURAMENTO", "Faturamento"), ("FINALIZACAO", "Finalizacao"), ("CANCELAMENTO", "Cancelamento"), ("OUTRO", "Outro")], db_index=True, default="OUTRO", max_length=20)),
                ("detalhe", models.TextField(blank=True, default="")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("usuario", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("venda", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="eventos", to="vendas.venda")),
            ],
            options={
                "ordering": ["-criado_em", "-id"],
                "indexes": [
                    models.Index(fields=["venda", "tipo"], name="idx_vendevento_venda_tipo"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VendaMovimentoEstoque",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo", models.CharField(choices=[("SAIDA", "Saida"), ("REVERSAO", "Reversao")], db_index=True, max_length=10)),
                ("quantidade", models.DecimalField(decimal_places=3, default=Decimal("0.000"), max_digits=14)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("item_venda", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="movimentos_estoque", to="vendas.itemvenda")),
                ("movimento", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="venda_link", to="estoque.estoquemovimento")),
                ("venda", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="movimentos_estoque", to="vendas.venda")),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["venda", "tipo"], name="idx_vendamov_venda_tipo"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("venda", "item_venda", "tipo"), name="uniq_venda_item_movtipo"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VendaRecebivel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero_parcela", models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(36)])),
                ("valor", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("data_vencimento", models.DateField(db_index=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("recebivel", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="venda_link", to="financeiro.recebivel")),
                ("venda", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recebiveis", to="vendas.venda")),
            ],
            options={
                "ordering": ["numero_parcela"],
                "indexes": [
                    models.Index(fields=["venda", "data_vencimento"], name="idx_vendarec_venda_venc"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("venda", "numero_parcela"), name="uniq_venda_parcela_recebivel"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VendaBoleto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero_parcela", models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(36)])),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("boleto", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="venda_link", to="boletos.boleto")),
                ("venda", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="boletos", to="vendas.venda")),
            ],
            options={
                "ordering": ["numero_parcela"],
                "constraints": [
                    models.UniqueConstraint(fields=("venda", "numero_parcela"), name="uniq_venda_parcela_boleto"),
                ],
            },
        ),
    ]

