# Generated by Django 6.0 on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="tipo_documento",
            field=models.CharField(
                choices=[("VENDA", "Venda"), ("ORCAMENTO", "Orcamento")],
                db_index=True,
                default="VENDA",
                max_length=15,
            ),
        ),
        migrations.AddIndex(
            model_name="venda",
            index=models.Index(fields=["tipo_documento", "data_venda"], name="idx_venda_doc_data"),
        ),
    ]

