# Generated by Django 6.0 on 2026-02-21

from django.db import migrations, models


def preencher_codigos(apps, schema_editor):
    Venda = apps.get_model("vendas", "Venda")
    for venda in Venda.objects.all().order_by("id"):
        prefixo = "ORC" if venda.tipo_documento == "ORCAMENTO" else "VEN"
        venda.codigo_identificacao = f"{prefixo}-{venda.id:06d}"
        venda.save(update_fields=["codigo_identificacao"])


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0002_venda_tipo_documento_idx_venda_doc_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="codigo_identificacao",
            field=models.CharField(blank=True, db_index=True, default="", max_length=20),
        ),
        migrations.RunPython(preencher_codigos, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="venda",
            name="codigo_identificacao",
            field=models.CharField(blank=True, db_index=True, default="", max_length=20, unique=True),
        ),
    ]

