# Generated by Django 6.0.2 on 2026-02-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_add_codigo_identificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='unidade_saida',
            field=models.CharField(choices=[('LOJA_1', 'FM COMERCIO - LOJA 1'), ('LOJA_2', 'ML COMERCIO - LOJA 2')], db_index=True, default='LOJA_1', max_length=20),
        ),
    ]
