# Generated by Django 6.0.2 on 2026-02-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_venda_unidade_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='unidade_saida',
            field=models.CharField(choices=[('LOJA_1', 'FM COMERCIO - UNIDADE 1'), ('LOJA_2', 'ML COMERCIO - UNIDADE 2')], db_index=True, default='LOJA_1', max_length=20),
        ),
    ]
