# Generated by Django 6.0.2 on 2026-02-24 15:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_alter_venda_unidade_saida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='tipo_pagamento',
            field=models.CharField(choices=[('PIX', 'PIX'), ('CREDITO', 'CREDITO'), ('DEBITO', 'DEBITO'), ('AVISTA', 'ESPECIE'), ('PARCELADO_BOLETO', 'BOLETO'), ('PARCELADO', 'CREDITO NA LOJA')], db_index=True, default='AVISTA', max_length=25),
        ),
        migrations.CreateModel(
            name='FechamentoCaixaDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField(db_index=True)),
                ('total_vendas', models.PositiveIntegerField(default=0)),
                ('total_receita', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_descontos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('totais_por_pagamento', models.JSONField(blank=True, default=dict)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('detalhes_json', models.JSONField(blank=True, default=dict)),
                ('arquivo_pdf', models.BinaryField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_caixa_vendas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_referencia', '-id'],
                'indexes': [models.Index(fields=['data_referencia', 'criado_em'], name='idx_fechcaixa_data_criado')],
            },
        ),
    ]
