# Generated by Django 6.0.2 on 2026-02-24 18:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_alter_venda_tipo_pagamento_fechamentocaixadiario'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pagamento', models.CharField(choices=[('PIX', 'PIX'), ('CREDITO', 'CREDITO'), ('DEBITO', 'DEBITO'), ('AVISTA', 'ESPECIE'), ('PARCELADO_BOLETO', 'BOLETO'), ('PARCELADO', 'CREDITO NA LOJA')], db_index=True, max_length=25)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='vendas.venda')),
            ],
            options={
                'ordering': ['-valor', 'id'],
                'indexes': [models.Index(fields=['venda', 'tipo_pagamento'], name='idx_vendapag_venda_tipo')],
                'constraints': [models.UniqueConstraint(fields=('venda', 'tipo_pagamento'), name='uniq_venda_tipopag')],
            },
        ),
    ]
