# Generated by Django 6.0.2 on 2026-02-18 05:35

import django.db.models.deletion
import financeiro.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conciliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AUTO', 'Automatica'), ('MANUAL', 'Manual')], default='MANUAL', max_length=10)),
                ('status_final', models.CharField(choices=[('PENDENTE', 'Pendente'), ('SUGERIDA', 'Sugerida'), ('CONCILIADA', 'Conciliada'), ('DIVERGENTE', 'Divergente'), ('IGNORADA', 'Ignorada')], max_length=20)),
                ('observacao', models.TextField(blank=True, default='')),
                ('conciliado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conciliado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliacoes_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-conciliado_em'],
            },
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('banco_codigo', models.CharField(blank=True, default='', max_length=10)),
                ('banco_nome', models.CharField(blank=True, default='', max_length=120)),
                ('agencia', models.CharField(max_length=20)),
                ('conta_numero', models.CharField(max_length=30)),
                ('conta_digito', models.CharField(blank=True, default='', max_length=5)),
                ('tipo_conta', models.CharField(choices=[('CORRENTE', 'Corrente'), ('POUPANCA', 'Poupanca'), ('OUTRA', 'Outra')], default='CORRENTE', max_length=20)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['banco_nome'], name='idx_fin_conta_banco_nome'), models.Index(fields=['conta_numero'], name='idx_fin_conta_numero')],
                'constraints': [models.UniqueConstraint(fields=('banco_codigo', 'agencia', 'conta_numero', 'conta_digito'), name='uniq_fin_conta_banco_ag_conta')],
            },
        ),
        migrations.CreateModel(
            name='ExtratoImportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_codigo', models.CharField(blank=True, default='', max_length=10)),
                ('banco_nome', models.CharField(blank=True, default='', max_length=120)),
                ('arquivo', models.FileField(upload_to=financeiro.models.ofx_upload_path)),
                ('arquivo_nome', models.CharField(blank=True, default='', max_length=255)),
                ('arquivo_sha256', models.CharField(db_index=True, max_length=64)),
                ('periodo_inicio', models.DateField(blank=True, null=True)),
                ('periodo_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PREVIEW', 'Preview'), ('SUCESSO', 'Sucesso'), ('PARCIAL', 'Parcial'), ('ERRO', 'Erro')], db_index=True, default='PREVIEW', max_length=20)),
                ('transacoes_detectadas', models.PositiveIntegerField(default=0)),
                ('transacoes_importadas', models.PositiveIntegerField(default=0)),
                ('transacoes_duplicadas', models.PositiveIntegerField(default=0)),
                ('alertas', models.JSONField(blank=True, default=list)),
                ('resumo', models.JSONField(blank=True, default=dict)),
                ('log_erro', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='importacoes', to='financeiro.contabancaria')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importacoes_extrato', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Recebivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('data_prevista', models.DateField(db_index=True)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('RECEBIDO', 'Recebido'), ('CANCELADO', 'Cancelado')], db_index=True, default='ABERTO', max_length=20)),
                ('origem_app', models.CharField(blank=True, default='', max_length=50)),
                ('origem_pk', models.PositiveBigIntegerField(blank=True, null=True)),
                ('referencia_externa', models.CharField(blank=True, default='', max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['data_prevista', 'id'],
                'indexes': [models.Index(fields=['status', 'data_prevista'], name='idx_fin_recebivel_status_dt')],
            },
        ),
        migrations.CreateModel(
            name='ConciliacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_alocado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('conciliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='financeiro.conciliacao')),
                ('recebivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conciliacoes', to='financeiro.recebivel')),
            ],
        ),
        migrations.CreateModel(
            name='TransacaoBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_lancamento', models.DateField(db_index=True)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tipo_movimento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saida')], db_index=True, max_length=10)),
                ('descricao', models.CharField(max_length=255)),
                ('external_id', models.CharField(blank=True, max_length=120, null=True)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('status_conciliacao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('SUGERIDA', 'Sugerida'), ('CONCILIADA', 'Conciliada'), ('DIVERGENTE', 'Divergente'), ('IGNORADA', 'Ignorada')], db_index=True, default='PENDENTE', max_length=20)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='financeiro.contabancaria')),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='financeiro.extratoimportacao')),
            ],
            options={
                'ordering': ['-data_lancamento', '-id'],
            },
        ),
        migrations.AddField(
            model_name='conciliacao',
            name='transacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='conciliacao', to='financeiro.transacaobancaria'),
        ),
        migrations.AddIndex(
            model_name='extratoimportacao',
            index=models.Index(fields=['status', 'criado_em'], name='idx_fin_imp_status_dt'),
        ),
        migrations.AddIndex(
            model_name='extratoimportacao',
            index=models.Index(fields=['conta', 'criado_em'], name='idx_fin_imp_conta_dt'),
        ),
        migrations.AddConstraint(
            model_name='conciliacaoitem',
            constraint=models.UniqueConstraint(fields=('conciliacao', 'recebivel'), name='uniq_fin_conc_item'),
        ),
        migrations.AddIndex(
            model_name='transacaobancaria',
            index=models.Index(fields=['conta', 'data_lancamento'], name='idx_fin_transacao_conta_dt'),
        ),
        migrations.AddIndex(
            model_name='transacaobancaria',
            index=models.Index(fields=['conta', 'valor'], name='idx_fin_transacao_conta_valor'),
        ),
        migrations.AddConstraint(
            model_name='transacaobancaria',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('conta', 'external_id'), name='uniq_fin_transacao_conta_external_id'),
        ),
        migrations.AddIndex(
            model_name='conciliacao',
            index=models.Index(fields=['status_final', 'conciliado_em'], name='idx_fin_conc_status_dt'),
        ),
    ]
