# Generated by Django 6.0.2 on 2026-02-13 03:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nome_normalizado', models.CharField(db_index=True, max_length=255)),
                ('cpf_cnpj', models.CharField(db_index=True, max_length=18, unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telefone', models.CharField(blank=True, default='', max_length=20)),
                ('endereco', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RamoAtuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('descricao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ramo de Atuação',
                'verbose_name_plural': 'Ramos de Atuação',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_boleto', models.CharField(db_index=True, max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('data_vencimento', models.DateField(db_index=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado'), ('PENDENTE', 'Pendente')], db_index=True, default='ABERTO', max_length=20)),
                ('comprovante_pagamento', models.FileField(blank=True, null=True, upload_to='boletos/comprovantes/')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletos_responsaveis', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos', to='boletos.cliente')),
            ],
            options={
                'ordering': ['-data_vencimento', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClienteListaNegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_bloqueio', models.DateField(auto_now_add=True, db_index=True)),
                ('motivo', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lista_negra', to='boletos.cliente')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloqueios_clientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente em Lista Negra',
                'verbose_name_plural': 'Clientes em Lista Negra',
                'ordering': ['-data_bloqueio'],
            },
        ),
        migrations.CreateModel(
            name='ControleFiado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('saldo_fiado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido'), ('BLOQUEADO', 'Bloqueado')], db_index=True, default='ATIVO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='controle_fiado', to='boletos.cliente')),
            ],
            options={
                'verbose_name': 'Controle de Fiado',
                'verbose_name_plural': 'Controle de Fiados',
            },
        ),
        migrations.CreateModel(
            name='ParcelaBoleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('data_vencimento', models.DateField(db_index=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado'), ('PENDENTE', 'Pendente')], db_index=True, default='ABERTO', max_length=20)),
                ('boleto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='boletos.boleto')),
            ],
            options={
                'ordering': ['numero_parcela'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='ramo_atuacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='boletos.ramoatuacao'),
        ),
        migrations.AddIndex(
            model_name='boleto',
            index=models.Index(fields=['numero_boleto'], name='idx_boleto_numero'),
        ),
        migrations.AddIndex(
            model_name='boleto',
            index=models.Index(fields=['cliente', 'status'], name='idx_boleto_cliente_status'),
        ),
        migrations.AddIndex(
            model_name='boleto',
            index=models.Index(fields=['data_vencimento'], name='idx_boleto_vencimento'),
        ),
        migrations.AddIndex(
            model_name='boleto',
            index=models.Index(fields=['vendedor'], name='idx_boleto_vendedor'),
        ),
        migrations.AlterUniqueTogether(
            name='parcelaboleto',
            unique_together={('boleto', 'numero_parcela')},
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nome_normalizado'], name='idx_cliente_nome_norm'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['cpf_cnpj'], name='idx_cliente_cpf_cnpj'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['ativo'], name='idx_cliente_ativo'),
        ),
    ]
