# Generated by Django 6.0.1 on 2026-02-04 12:56

import compras.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nome_normalizado', models.CharField(db_index=True, max_length=255, unique=True)),
                ('cnpj', models.CharField(blank=True, db_index=True, default='', max_length=18)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome_normalizado'], name='idx_fornecedor_nome_norm'), models.Index(fields=['cnpj'], name='idx_fornecedor_cnpj')],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_custo', models.CharField(choices=[('FM', 'FM'), ('ML', 'ML'), ('PESSOAL', 'PESSOAL'), ('FM/ML', 'FM/ML'), ('OUTROS', 'OUTROS')], db_index=True, max_length=20)),
                ('data_compra', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('nota_fiscal', models.FileField(blank=True, null=True, upload_to=compras.models.compra_upload_path)),
                ('valor_total', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='compras.fornecedor')),
            ],
            options={
                'ordering': ['-data_compra', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FornecedorAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nome_normalizado', models.CharField(db_index=True, max_length=255, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='compras.fornecedor')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.compra')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=compras.models.garantia_upload_path)),
                ('data_inicio', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('data_fim', models.DateField(db_index=True)),
                ('observacao', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garantias', to='compras.itemcompra')),
            ],
            options={
                'ordering': ['-data_fim', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nome_normalizado', models.CharField(db_index=True, max_length=255)),
                ('sku', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome_normalizado'], name='idx_prod_nome_norm'), models.Index(fields=['sku'], name='idx_prod_sku')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('sku',), name='uniq_prod_sku_when_filled')],
            },
        ),
        migrations.AddField(
            model_name='itemcompra',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_compra', to='compras.produto'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['data_compra'], name='idx_compra_data'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['centro_custo', 'data_compra'], name='idx_compra_cc_data'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['fornecedor', 'data_compra'], name='idx_compra_forn_data'),
        ),
        migrations.AddIndex(
            model_name='fornecedoralias',
            index=models.Index(fields=['nome_normalizado'], name='idx_fornalias_nome_norm'),
        ),
        migrations.AddIndex(
            model_name='fornecedoralias',
            index=models.Index(fields=['principal'], name='idx_fornalias_principal'),
        ),
        migrations.AddIndex(
            model_name='garantia',
            index=models.Index(fields=['data_fim'], name='idx_garantia_data_fim'),
        ),
        migrations.AddIndex(
            model_name='garantia',
            index=models.Index(fields=['item'], name='idx_garantia_item'),
        ),
        migrations.AddIndex(
            model_name='itemcompra',
            index=models.Index(fields=['compra'], name='idx_item_compra'),
        ),
        migrations.AddIndex(
            model_name='itemcompra',
            index=models.Index(fields=['produto'], name='idx_item_produto'),
        ),
    ]
