# Generated by Django 6.0.2 on 2026-02-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='boleto',
            field=models.FileField(blank=True, null=True, upload_to='compras/boletos/'),
        ),
        migrations.AddField(
            model_name='compra',
            name='pedido',
            field=models.FileField(blank=True, null=True, upload_to='compras/pedidos/'),
        ),
    ]
