# Generated by Django 6.0.2 on 2026-02-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compra_boleto_compra_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='comprovante_pagamento',
            field=models.FileField(blank=True, null=True, upload_to='compras/comprovantes/'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='contato_representante',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='representante_comercial',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='telefone_contato',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
