# Generated by Django 6.0 on 2026-02-21

import compras.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0007_add_compra_status_evento"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="justificativa_escolha",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="compra",
            name="orcamento_1",
            field=models.FileField(blank=True, null=True, upload_to=compras.models.orcamento_upload_path),
        ),
        migrations.AddField(
            model_name="compra",
            name="orcamento_2",
            field=models.FileField(blank=True, null=True, upload_to=compras.models.orcamento_upload_path),
        ),
        migrations.AddField(
            model_name="compra",
            name="orcamento_3",
            field=models.FileField(blank=True, null=True, upload_to=compras.models.orcamento_upload_path),
        ),
        migrations.AddField(
            model_name="compra",
            name="orcamento_escolhido",
            field=models.CharField(
                blank=True,
                choices=[("ORC_1", "Orcamento 1"), ("ORC_2", "Orcamento 2"), ("ORC_3", "Orcamento 3")],
                db_index=True,
                default="",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="compra",
            index=models.Index(fields=["orcamento_escolhido", "data_compra"], name="idx_compra_orc_data"),
        ),
    ]

